
# Session 12 - Text sentimental

 Sparse matrix :
A matrix is a two-dimensional data object made of m rows and n columns, therefore having total m x n values. If most of the elements of the matrix have 0 value, then it is called a sparse matrix. (like: vectorizer, tf-idf and onehotecode)

----------------------------

Embedding for text : differ from vectorizer : help keep semantic

Text embeddings are vector representations of text that map the original text into a mathematical space where words or sentences with similar meanings are located near each other. Unlike traditional one-hot encoding, where each word is represented as a sparse vector with a single '1' for the corresponding word and '0's elsewhere, text embeddings allow for more nuanced representations, capturing relationships and meanings of words.

---------------------------------------------------

n-grams in tfidf

Term Frequency-Inverse Document Frequency (TF-IDF) is a widely used technique in NLP for converting textual data into vectors (numerical representation). Usually TF-IDF works with single words also known as unigrams. But we can also use it for bigrams i.e pairs of words and trigrams i.e groups of three words. This helps in capturing more meaning and context from the text.

----------------------------

Embedding:

In machine learning, embeddings are a way of representing data as numerical vectors in a continuous space. They capture the meaning or relationship between data points, so that similar items are placed closer together while dissimilar ones are farther apart. This makes it easier for algorithms to work with complex data such as words, images or audio

-----------------------------

Image Embedding:

An image embedding is a numeric representation of an image that encodes the semantics of contents in the image. Embeddings are calculated by computer vision models which are usually trained with large datasets of pairs of text and image. The goal of such a model is to build an "understanding" of the relationship between images and text.

--------------------------------------

Function Transform

Wraps any Python function into a sklearn transformer.

A Transformer = Any Object with .fit() and .transform() Methods

---------------------

Imbalance Data in Classification

How handle it:

1- Under Sampling : Reduce the number of sample in he class with large amount to make classes balanced

2- Over sampling : Increase the number of samples in the classes with lower number ( there are some approaches for this matter)

3- adding weight to punish more loss on class with lower sample (for loss mutiple in 2 for each loss you get)

-----------

## Working on topics for myself (out of class materials )

In [188]:
#Plain function:   np.log, preprocess, batch_preprocess
 #                 → Can use alone, but NOT in Pipeline
#
#sklearn transformer: StandardScaler, TfidfVectorizer,
 #                     FunctionTransformer(np.log)
  #                → Has .fit() + .transform() → Works in Pipeline

#Function Transformer Example
import numpy as np
from Bio.Phylo.NewickIO import tokenizer
from sklearn.preprocessing import FunctionTransformer
from tensorflow.python.ops.ragged.ragged_string_ops import ngrams

X = np.array([[1,2,3],[4,5,6],[7,8,9]])
# Any function → sklearn transformer!
transformer = FunctionTransformer(np.log)
X_log = transformer.fit_transform(X)
print(X_log)
np.log(X)

[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]
 [1.94591015 2.07944154 2.19722458]]

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [9]:
#Imbalance Data work

In [7]:
import numpy as np
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import FunctionTransformer, StandardScaler
from sklearn.linear_model import LinearRegression

X = np.array([10, 20, 30, 40, 50, 50, 70, 80, 90]).reshape(-1, 1)
y = np.array([12, 24, 37, 40, 54, 63, 72, 81, 91])

pipeline = Pipeline([
    ('log', FunctionTransformer(np.log)),
    ('scaler', StandardScaler()),
    ('model', LinearRegression())
])

pipeline.fit(X, y)
print("Score:", pipeline.score(X, y))

Score: 0.9235902203233952

In [30]:
from sklearn.datasets import make_blobs

X, y = make_blobs(n_samples=50, n_features=2, centers=2, random_state=0)
np.unique(y,return_counts=True)

(array([0, 1]), array([25, 25], dtype=int64))

In [43]:
#imbalanced
y[10:50] = 1
print(y)
np.unique(y,return_counts=True)

[1 1 0 0 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1]

(array([0, 1]), array([ 3, 47], dtype=int64))

In [32]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [33]:
X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                     test_size=0.3, stratify=y)

In [42]:
# without handling
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

model = LogisticRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

report = classification_report(y_test, y_pred)
print(report)

#underfit

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.93      1.00      0.97        14

    accuracy                           0.93        15
   macro avg       0.47      0.50      0.48        15
weighted avg       0.87      0.93      0.90        15

C:\Users\top\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\top\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\top\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [47]:
# handle with class weight
from sklearn.linear_model import LogisticRegression
model2 = LogisticRegression(class_weight='balanced')
model2.fit(X_train, y_train)
y_pred = model2.predict(X_test)
print(classification_report(y_test, y_pred))

#now it better

              precision    recall  f1-score   support

           0       0.25      1.00      0.40         1
           1       1.00      0.79      0.88        14

    accuracy                           0.80        15
   macro avg       0.62      0.89      0.64        15
weighted avg       0.95      0.80      0.85        15

In [57]:
from sklearn.linear_model import LogisticRegression
model2 = LogisticRegression(class_weight={0:50,1:1})
model2.fit(X_train, y_train)
y_pred = model2.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.14      1.00      0.25         1
           1       1.00      0.57      0.73        14

    accuracy                           0.60        15
   macro avg       0.57      0.79      0.49        15
weighted avg       0.94      0.60      0.70        15

In [62]:
# Over sampling
from imblearn.under_sampling import RandomUnderSampler
rus = RandomUnderSampler(random_state=42)
X_under, y_under = rus.fit_resample(X_train, y_train)

model = LogisticRegression()
model.fit(X_under, y_under)
y_pred = model.predict(X_test)
print(classification_report(y_test, y_pred))

X_under, y_under

              precision    recall  f1-score   support

           0       0.11      1.00      0.20         1
           1       1.00      0.43      0.60        14

    accuracy                           0.47        15
   macro avg       0.56      0.71      0.40        15
weighted avg       0.94      0.47      0.57        15

(array([[2.47034915, 4.09862906],
        [1.7373078 , 4.42546234],
        [2.02708529, 1.32599553],
        [2.06576754, 2.68353415]]),
 array([0, 0, 1, 1]))

In [72]:
#Oversampling
from imblearn.over_sampling import RandomOverSampler
from imblearn.over_sampling import RandomOverSampler
ros = RandomOverSampler(random_state=42)
X_ros, y_ros = ros.fit_resample(X_train, y_train)

model3 = LogisticRegression()
model3.fit(X_ros, y_ros)
y_pred3 = model3.predict(X_test)
print(classification_report(y_test, y_pred3))

y_ros

              precision    recall  f1-score   support

           0       0.25      1.00      0.40         1
           1       1.00      0.79      0.88        14

    accuracy                           0.80        15
   macro avg       0.62      0.89      0.64        15
weighted avg       0.95      0.80      0.85        15

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Class Material

In [73]:
#Sentimental Analysis

In [1]:
import re

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from parsivar import Tokenizer, Normalizer, FindStems

from sklearn.pipeline import Pipeline, FunctionTransformer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import GridSearchCV, StratifiedKFold

from sklearn.svm import LinearSVC

from sklearn.metrics import classification_report

In [2]:
train_df = pd.read_csv('train.csv',delimiter="\t")
train_df

#Delimiter = The symbol that splits one column from another
#The file uses TABS to separate columns, not commas. When text contains commas, CSV splitting breaks. Tab splitting works.

,Unnamed: 0,comment,label,label_id
0,0,واقعا حیف وقت که بنویسم سرویس دهیتون شده افتضاح,SAD,1
1,1,قرار بود ۱ ساعته برسه ولی نیم ساعت زودتر از مو...,HAPPY,0
2,2,قیمت این مدل اصلا با کیفیتش سازگاری نداره، فقط...,SAD,1
3,3,عالللی بود همه چه درست و به اندازه و کیفیت خوب...,HAPPY,0
4,4,شیرینی وانیلی فقط یک مدل بود.,HAPPY,0
...,...,...,...,...
56695,56695,یک تیکه کم فرستاده بودن و با تماس من در کمترین...,HAPPY,0
56696,56696,عالی بود همه چیز ممنونم پیک هم خیلی مرتب و به ...,HAPPY,0
56697,56697,مثل همیشه عالی، من چندمین باره سفارش میدم و هر...,HAPPY,0
56698,56698,دلستر استوایی خواسته بودم اما لیمویی فرستادند,HAPPY,0
56699,56699,جای مرغ گریل شده ناگت بود، به این نمی‌گن چیکن ...,SAD,1

In [3]:
X  = train_df ['comment']
# 0 = happy 1= Sad
X

0          واقعا حیف وقت که بنویسم سرویس دهیتون شده افتضاح
1        قرار بود ۱ ساعته برسه ولی نیم ساعت زودتر از مو...
2        قیمت این مدل اصلا با کیفیتش سازگاری نداره، فقط...
3        عالللی بود همه چه درست و به اندازه و کیفیت خوب...
4                            شیرینی وانیلی فقط یک مدل بود.
                               ...
56695    یک تیکه کم فرستاده بودن و با تماس من در کمترین...
56696    عالی بود همه چیز ممنونم پیک هم خیلی مرتب و به ...
56697    مثل همیشه عالی، من چندمین باره سفارش میدم و هر...
56698        دلستر استوایی خواسته بودم اما لیمویی فرستادند
56699    جای مرغ گریل شده ناگت بود، به این نمی‌گن چیکن ...
Name: comment, Length: 56700, dtype: object

In [4]:
y = train_df['label_id']
np.unique(y,return_counts=True)

(array([0, 1], dtype=int64), array([28350, 28350], dtype=int64))

In [5]:
# using stop words
with open ('stopwords.dat','rt',encoding='UTF-8') as file:
    stopwords = file.read().splitlines()

print(stopwords)
text = 'این یک متن نمونه است'
words = text.split()
print(words)
filter  = [w for w in words if w not in stopwords]

filter
#UTF-8 understands Persian

['و', 'در', 'به', 'از', 'که', 'این', 'را', 'با', 'است', 'برای', 'آن', 'یک', 'خود', 'تا', 'کرد', 'بر', 'هم', 'نیز', 'گفت', 'می\u200cشود', 'وی', 'شد', 'دارد', 'ما', 'اما', 'یا', 'شده', 'باید', 'هر', 'آنها', 'بود', 'او', 'دیگر', 'دو', 'مورد', 'می\u200cکند', 'شود', 'کند', 'وجود', 'بین', 'پیش', 'شده_است', 'پس', 'نظر', 'اگر', 'همه', 'یکی', 'حال', 'هستند', 'من', 'کنند', 'نیست', 'باشد', 'چه', 'بی', 'می', 'بخش', 'می\u200cکنند', 'همین', 'افزود', 'هایی', 'دارند', 'راه', 'همچنین', 'روی', 'داد', 'بیشتر', 'بسیار', 'سه', 'داشت', 'چند', 'سوی', 'تنها', 'هیچ', 'میان', 'اینکه', 'شدن', 'بعد', 'جدید', 'ولی', 'حتی', 'کردن', 'برخی', 'کردند', 'می\u200cدهد', 'اول', 'نه', 'کرده_است', 'نسبت', 'بیش', 'شما', 'چنین', 'طور', 'افراد', 'تمام', 'درباره', 'بار', 'بسیاری', 'می\u200cتواند', 'کرده', 'چون', 'ندارد', 'دوم', 'بزرگ', 'طی', 'حدود', 'همان', 'بدون', 'البته', 'آنان', 'می\u200cگوید', 'دیگری', 'خواهد_شد', 'کنیم', 'قابل', 'یعنی', 'رشد', 'می\u200cتوان', 'وارد', 'کل', 'ویژه', 'قبل', 'براساس', 'نیاز', 'گذاری', 'هنوز', 'لازم', 'سازی', 'بوده_است', 'چرا', 'می\u200cشوند', 'وقتی', 'گرفت', 'کم', 'جای', 'حالی', 'تغییر', 'پیدا', 'اکنون', 'تحت', 'باعث', 'مدت', 'فقط', 'زیادی', 'تعداد', 'آیا', 'بیان', 'رو', 'شدند', 'عدم', 'کرده_اند', 'بودن', 'نوع', 'بلکه', 'جاری', 'دهد', 'برابر', 'مهم', 'بوده', 'اخیر', 'مربوط', 'امر', 'زیر', 'گیری', 'شاید', 'خصوص', 'آقای', 'اثر', 'کننده', 'بودند', 'فکر', 'کنار', 'اولین', 'سوم', 'سایر', 'کنید', 'ضمن', 'مانند', 'باز', 'می\u200cگیرد', 'ممکن', 'حل', 'دارای', 'پی', 'مثل', 'می\u200cرسد', 'اجرا', 'دور', 'منظور', 'کسی', 'موجب', 'طول', 'امکان', 'آنچه', 'تعیین', 'گفته', 'شوند', 'جمع', 'خیلی', 'علاوه', 'گونه', 'تاکنون', 'رسید', 'ساله', 'گرفته', 'شده_اند', 'علت', 'چهار', 'داشته_باشد', 'خواهد_بود', 'طرف', 'تهیه', 'تبدیل', 'مناسب', 'زیرا', 'مشخص', 'می\u200cتوانند', 'نزدیک', 'جریان', 'روند', 'بنابراین', 'می\u200cدهند', 'یافت', 'نخستین', 'بالا', 'پنج', 'ریزی', 'عالی', 'چیزی', 'نخست', 'بیشتری', 'ترتیب', 'شده_بود', 'خاص', 'خوبی', 'خوب', 'شروع', 'فرد', 'کامل', 'غیر', 'می\u200cرود', 'دهند', 'آخرین', 'دادن', 'جدی', 'بهترین', 'شامل', 'گیرد', 'بخشی', 'باشند', 'تمامی', 'بهتر', 'داده_است', 'حد', 'نبود', 'کسانی', 'می\u200cکرد', 'داریم', 'علیه', 'می\u200cباشد', 'دانست', 'ناشی', 'داشتند', 'دهه', 'می\u200cشد', 'ایشان', 'آنجا', 'گرفته_است', 'دچار', 'می\u200cآید', 'لحاظ', 'آنکه', 'داده', 'بعضی', 'هستیم', 'اند', 'برداری', 'نباید', 'می\u200cکنیم', 'نشست', 'سهم', 'همیشه', 'آمد', 'اش', 'وگو', 'می\u200cکنم', 'حداقل', 'طبق', 'جا', 'خواهد_کرد', 'نوعی', 'چگونه', 'رفت', 'هنگام', 'فوق', 'روش', 'ندارند', 'سعی', 'بندی', 'شمار', 'کلی', 'کافی', 'مواجه', 'همچنان', 'زیاد', 'سمت', 'کوچک', 'داشته_است', 'چیز', 'پشت', 'آورد', 'حالا', 'روبه', 'سال\u200cهای', 'دادند', 'می\u200cکردند', 'عهده', 'نیمه', 'جایی', 'دیگران', 'سی', 'بروز', 'یکدیگر', 'آمده_است', 'جز', 'کنم', 'سپس', 'کنندگان', 'خودش', 'همواره', 'یافته', 'شان', 'صرف', 'نمی\u200cشود', 'رسیدن', 'چهارم', 'یابد', 'متر', 'ساز', 'داشته', 'کرده_بود', 'باره', 'نحوه', 'کردم', 'تو', 'شخصی', 'داشته_باشند', 'محسوب', 'پخش', 'کمی', 'متفاوت', 'سراسر', 'کاملا', 'داشتن', 'نظیر', 'آمده', 'گروهی', 'فردی', 'ع', 'همچون', 'خطر', 'خویش', 'کدام', 'دسته', 'سبب', 'عین', 'آوری', 'متاسفانه', 'بیرون', 'دار', 'ابتدا', 'شش', 'افرادی', 'می\u200cگویند', 'سالهای', 'درون', 'نیستند', 'یافته_است', 'پر', 'خاطرنشان', 'گاه', 'جمعی', 'اغلب', 'دوباره', 'می\u200cیابد', 'لذا', 'زاده', 'گردد', 'اینجا']
['این', 'یک', 'متن', 'نمونه', 'است']

['متن', 'نمونه']

In [6]:
normalizer = Normalizer()
my_tokenizer = Tokenizer()
text = 'ایِنـ    یک متن نمونه است'
print(text)
print(normalizer.normalize(text))
print(my_tokenizer.tokenize_words(text))
text_nor  = normalizer.normalize(text)
my_tokenizer.tokenize_words(text_nor)

ایِنـ    یک متن نمونه است
این یک متن نمونه است
['ایِنـ', 'یک', 'متن', 'نمونه', 'است']

['این', 'یک', 'متن', 'نمونه', 'است']

In [7]:
import re
# Types of regex

# 1- first \d means remove digits
text  = "سلام 123خوبی"
print(re.sub(r'\d',"",text))


#2-  r"[^\w\s\u0600-\u06FF]"
 # ^ not
 # \w : English letters (a-z, A-Z), digits (0-9), underscore (_)
 # \s : spaces , tabs. newlines
 # \u0600-\u06FF : Persian/Arabic Unicode range (Persian letters)
pattern = r"[^\w\s\u0600-\u06FF]"

# Example 1: Punctuation removed
text1 = "سلام! چطوری؟"
print(re.sub(pattern, " ", text1))

# Example 2: Special characters removed
text2 = "price: 100$ #discount @shop"
print(re.sub(pattern, " ", text2))

# Example 3: Emojis removed
text3 = "عالی 😍 خیلی خوب 👌"
print(re.sub(pattern, " ", text3))

#Example 4: Mixed Persian + English + symbols
text4 = "قیمت: 100$ برای book #جدید"
print(re.sub(pattern, " ", text4))



# 3 Remove Repeated Characters: text = re.sub(r"(.)\1{2,}", r"\1", text)

#(.)      = Capture any character
#\1{2,}   = Same character repeated 2+ more times
#\1       = Replace with ONE copy
text  = 'برررسی'
print(re.sub(r'(.)\1{2,}',r'\1', text))


#Remove Extra Spaces + Trim
#text = re.sub(r"\s+", " ", text).strip()
#.strip() — Remove spaces at START and END only
text  = '  سلام  چه ط.ری     ؟  '
print(re.sub(r'\s+', ' ', text))
print(re.sub(r'\s+', ' ', text).strip())

سلام خوبی
سلام  چطوری؟
price  100   discount  shop
عالی   خیلی خوب
قیمت  100  برای book  جدید
برسی
 سلام چه ط.ری ؟
سلام چه ط.ری ؟

In [8]:
X.iloc[1]

'قرار بود ۱ ساعته برسه ولی نیم ساعت زودتر از موقع رسید، شما ببین چقدرررررررررررر پلاک خفنههههه، من سالهاست مشتریشونم و سالهاست مزه بهشت میده غذاشون'

In [22]:
# Build a preprocessing function for persian texts (Save as Class for future work on Classes )
import re
normalizer=normalizer
tokenizer=my_tokenizer
def preprocess(text):
    text = normalizer.normalize(text)
    text = re.sub(r'[^\w\s\u0600-\u06FF]', ' ', text)
    text = re.sub(r"\u200c", " ", text)
    text = re.sub(r'[؟،؛٪]', ' ', text)
    text = re.sub(r"(.)\1{2,}", r"\1", text)
    text = re.sub(r"\s+", " ", text).strip()
    tokens = [word for word in tokenizer.tokenize_words(text) if word not in stopwords]
    return " ".join(tokens) if len(tokens) > 0 else ""

#batch_preprocess — Runs preprocess_text on MULTIPLE texts at once
def batch_preprocess(texts):
    return [preprocess(txt) for txt in texts]

# or you can use apply on th columns you want

In [10]:
 # example of batch pre
text1 = preprocess("سلام چطوری؟")
text2 = preprocess("خوبم مرسی!")
text3 = preprocess("چه خبر؟")

print(text1,text2,text3)

# Fix batch_preprocess first:
def batch_preprocess(texts):
    return [preprocess(txt) for txt in texts]

# Then use it:
texts = ["سلام چطوری؟", "خوبم مرسی!", "چه خبر؟"]
clean = batch_preprocess(texts)  # No extra brackets!
print(clean)  # 'سلام چطوری'

سلام چطوری خوبم مرسی خبر
['سلام چطوری', 'خوبم مرسی', 'خبر']

In [11]:
tfidf = TfidfVectorizer(
    max_features=50000, #Keep only the top 50,000 most frequent words.
    min_df=3, #Ignore words that appear in fewer than 3 documents.
    max_df=.9, # Ignore words that appear in more than 90% of documents.
    ngram_range=(1, 3) #Creates 1-word, 2-word, and 3-word phrases as features.
)
tfidf


#Unigrams (1):  "غذای", "خوب", "خوردم"
#Bigrams (2):   "غذای خوب", "خوب خوردم"
#Trigrams (3):  "غذای خوب خوردم"

TfidfVectorizer(max_df=0.9, max_features=50000, min_df=3, ngram_range=(1, 3))

In [12]:
model = LinearSVC(C=0.3)

base_pipeline = ([
    ('text_preprocess', FunctionTransformer(batch_preprocess)),
    ('tfidf',tfidf),
    ('Classifier', model)
])

base_pipeline

[('text_preprocess',
  FunctionTransformer(func=<function batch_preprocess at 0x000002B5417BAC00>)),
 ('tfidf',
  TfidfVectorizer(max_df=0.9, max_features=50000, min_df=3, ngram_range=(1, 3))),
 ('Classifier', LinearSVC(C=0.3))]

In [13]:
#or
from sklearn.base import BaseEstimator, TransformerMixin
class BatchPreprocessor(BaseEstimator, TransformerMixin):
    def __init__(self):
        pass

    def fit(self, X, y=None):
        return self  # Nothing to learn

    def transform(self, X, y=None):
        return [preprocess(text) for text in X]


base_pipeline = ([
    ('text_preprocess',BatchPreprocessor() )
])

In [14]:
ase_pipeline = ([
    ('text_preprocess',BatchPreprocessor() )
])

In [15]:
# or
tfidf = TfidfVectorizer(
    max_features=50000,
    min_df=3,
    max_df=0.9,
    ngram_range=(1, 3),
    preprocessor=batch_preprocess  # ← Preprocess inside TF-IDF!
)

# Simpler pipeline — no need for preprocess step!
base_pipeline = Pipeline([
    ('tfidf', tfidf),
    ('Classifier', model)
])

In [16]:
print(X.shape)  # Should be (56700,)
print(y.shape)

(56700,)
(56700,)

### # This code doesnt work

In [ ]:
# grid model best params
base_pipeline = Pipeline([                  # ← Pipeline() wraps the list
    ('text_preprocess', FunctionTransformer(batch_preprocess)),
    ('tfidf', tfidf),
    ('Classifier', model)
])


skf = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)


grid_model  = GridSearchCV(
    base_pipeline,
    param_grid={
        "tfidf__ngram_range": [(1, 1), (1, 2), (1, 3)],
        "tfidf__min_df": [1, 3, 5, 10, 20],
        "tfidf__max_df": [0.8, 0.9, 0.95, 1.0],
        "Classifier__C": [0.01, 0.1, 1, 5, 10]
    },
    scoring="f1_macro",
    verbose=3,
    cv=skf

)
grid_model.fit(X,y)
best_estimator = grid_model.best_estimator_


# This code doesnt work

Fitting 3 folds for each of 300 candidates, totalling 900 fits
[CV 1/3] END Classifier__C=0.01, tfidf__max_df=0.8, tfidf__min_df=1, tfidf__ngram_range=(1, 1);, score=nan total time=   6.0s
[CV 2/3] END Classifier__C=0.01, tfidf__max_df=0.8, tfidf__min_df=1, tfidf__ngram_range=(1, 1);, score=nan total time=   6.1s

### Fixed code

In [1]:
import re
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from parsivar import Tokenizer, Normalizer, FindStems

from sklearn.pipeline import Pipeline, FunctionTransformer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import GridSearchCV, StratifiedKFold
from sklearn.svm import LinearSVC
from sklearn.metrics import classification_report

# ===== 1. Load Data =====
train_df = pd.read_csv('train.csv', delimiter="\t")
X = train_df['comment']
y = train_df['label_id']

# ===== 2. FIX: Initialize tools BEFORE the function =====
normalizer = Normalizer()
my_tokenizer = Tokenizer()

# If you don't have a stopwords file yet, we use an empty list so it doesn't crash.
# If you do, load it here.
stopwords = []

# ===== 3. FIX: Safely define the preprocessing function =====
def preprocess(text):
    # Added string conversion to prevent crashes on NaN or missing data
    text = str(text)
    text = normalizer.normalize(text)
    text = re.sub(r'\d+', ' ', text)
    text = re.sub(r'[^\w\s\u0600-\u06FF]', ' ', text)
    text = re.sub(r"\u200c", " ", text)
    text = re.sub(r'[؟،؛٪]', ' ', text)
    text = re.sub(r"(.)\1{2,}", r"\1", text)
    text = re.sub(r"\s+", " ", text).strip()

    tokens = [word for word in my_tokenizer.tokenize_words(text) if word not in stopwords]

    # FIX: Prevent returning completely empty strings
    result = " ".join(tokens)
    return result if len(result) > 0 else " "  #because if here the last one was broken

def batch_preprocess(texts):
    return [preprocess(txt) for txt in texts]

# ===== 4. Setup Pipeline =====
tfidf = TfidfVectorizer(
    max_features=50000,
    min_df=3,
    max_df=.9,
    ngram_range=(1, 3)
)

model = LinearSVC(C=0.3)

# FIX: Define the pipeline correctly just once
base_pipeline = Pipeline([
    ('text_preprocess', FunctionTransformer(batch_preprocess)),
    ('tfidf', tfidf),
    ('Classifier', model)
])

skf = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)

# ===== 5. Run GridSearch =====
grid_model = GridSearchCV(
    base_pipeline,
    param_grid = {
        "tfidf__ngram_range": [(1, 1), (1, 2)],
        "tfidf__min_df": [1, 3, 5],
        "tfidf__max_df": [0.8, 0.95, 1.0],
        "Classifier__C": [0.1, 1, 10]
    },
    scoring="f1_macro",
    verbose=3,
    cv=skf,
    n_jobs=-1  # FIX: Added n_jobs=-1 to use all CPU cores and speed up the heavy processing
)

grid_model.fit(X, y)
best_estimator = grid_model.best_estimator_

print("\nBest Parameters found:", grid_model.best_params_)

Fitting 3 folds for each of 54 candidates, totalling 162 fits

Best Parameters found: {'Classifier__C': 0.1, 'tfidf__max_df': 0.8, 'tfidf__min_df': 3, 'tfidf__ngram_range': (1, 2)}

In [6]:
test_df  = pd.read_csv('test.csv', delimiter="\t")
X_test = test_df['comment']
y_test = test_df['label_id']
X_test

0       خواهشا خواهشا خواهشا واسه ارسال شیرینیها یه فک...
1                  غذا گرم رسید کیفیت و پخت گوشت عالی بود
2       قیمت سس شکلات روی بسته بندی ۱۵۰۰۰ بود ولی قیمت...
3       عکس توی پیج یه شیرینی شکری روشن رنگ هست که همم...
4                 باز هم میگم، پیتزا نباید اینقد چرب باشه
                              ...
6995    سطح پیتزا سوخته بود متاسفانه و ارزش اون پولو ن...
6996                          بسته بندی خیلی بسیار بد شده
6997    سلام خسته نباشید همه چی خوب بود فقط یک مقدار م...
6998                       غذا سرد و کیفیت قابل قبول نبود
6999                یه کم خشک بود ولی در مجموع خوشمزه بود
Name: comment, Length: 7000, dtype: object

In [7]:
y_pred = best_estimator.predict(X_test)

In [9]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.90      0.82      0.86      3500
           1       0.84      0.91      0.87      3500

    accuracy                           0.87      7000
   macro avg       0.87      0.87      0.86      7000
weighted avg       0.87      0.87      0.86      7000

In [13]:
feature_names = best_estimator.named_steps["tfidf"].get_feature_names_out()
weights = best_estimator.named_steps["Classifier"].coef_[0]
weights

array([ 0.02107373, -0.01626938, -0.02765001, ..., -0.04544847,
       -0.07657872, -0.05856517])

In [14]:
importances = pd.DataFrame({
    "feature": feature_names,
    "weight": weights,
})
importances

        feature    weight
0            00  0.021074
1            05 -0.016269
2      05 دقیقه -0.027650
3            09 -0.012953
4            10  0.181022
...         ...       ...
49995    یکیشون  0.179260
49996      یکیم -0.028503
49997      یکیه -0.045448
49998        یی -0.076579
49999     یی که -0.058565

[50000 rows x 2 columns]

In [15]:
importances = importances.sort_values(by="weight", ascending=True)
importances

# - is good + is bad

      feature    weight
27457    عالی -4.712198
17717  خوشمزه -2.826825
17225     خوب -2.795224
33506   ممنون -2.503814
27683   عالیه -2.431534
...       ...       ...
22543    ساعت  1.514904
8086   بدترین  1.635900
41428   پایین  1.687416
3661   افتضاح  1.820880
3214     اصلا  2.249517

[50000 rows x 2 columns]

In [17]:
positives = importances.sort_values(by="weight", ascending=True).head(50)
positives

            feature    weight
27457          عالی -4.712198
17717        خوشمزه -2.826825
17225           خوب -2.795224
33506         ممنون -2.503814
27683         عالیه -2.431534
23548          سریع -1.976210
33552        ممنونم -1.928138
10954        بهترین -1.881157
46005           کمی -1.800458
17381          خوبه -1.788297
8036        بد نبود -1.757938
17255       خوب بود -1.704507
14437          تشکر -1.698451
17738    خوشمزه بود -1.540664
17670           خوش -1.536041
3884     العاده بود -1.506216
49859           یکم -1.368611
32335          مرسی -1.342591
6816       با کیفیت -1.336614
10862          بهتر -1.325910
27497      عالی بود -1.235185
29087           فقط -1.167652
20596     راضی بودم -1.167445
24934          سپاس -1.156367
30603          لذیذ -1.146198
20610         راضیم -1.138143
23433          سرعت -1.081059
44346           کاش -1.050886
10737       به موقع -1.036915
24944     سپاسگزارم -1.028265
20592          راضی -0.957155
33916         مناسب -0.953981
17400          خوبی -0.949902
17712        خوشمزس -0.937479
17413     خوبی داشت -0.926052
16498           حرف -0.911394
13676          تازه -0.909420
37517          نظیر -0.908108
17960      خیلی خوب -0.904464
9608   بسیار خوشمزه -0.903690
22214           زود -0.894476
17408      خوبی بود -0.880623
31556        متشکرم -0.869931
30584           لذت -0.866228
34499          موقع -0.859672
11709       بود فقط -0.848501
18752           داغ -0.847052
13701      تازه بود -0.841679
34375          مودب -0.837132
19136         در کل -0.816337

In [18]:
negative = importances.sort_values(by="weight", ascending=False).head(50)
negative

           feature    weight
3214          اصلا  2.249517
3661        افتضاح  1.820880
41428        پایین  1.687416
8086        بدترین  1.635900
22543         ساعت  1.514904
23285          سرد  1.446039
31514       متاسفم  1.425791
7960            بد  1.420412
17334     خوب نبود  1.342483
17793  خوشمزه نبود  1.319287
12924     بی کیفیت  1.289682
34593        مونده  1.285319
36318         نبود  1.255302
24725        سوخته  1.180984
36833        نداشت  1.141978
47307         کهنه  1.139731
38228        نپخته  1.134318
8174         بدمزه  1.126510
16723          خام  1.117874
17420   خوبی نداشت  1.116950
23911        سفارش  1.111761
36593        نبودم  1.075773
20602   راضی نبودم  1.066936
12867           بی  1.049916
42175          پول  1.036782
7982        بد بود  1.015255
12932         بیات  0.975478
17092         خمیر  0.967905
35881       ناراضی  0.946151
31167        مانده  0.940492
35980      نامناسب  0.935232
28925      فرستادن  0.930230
33363       مغایرت  0.895724
35011        میداد  0.869649
26159          شور  0.867780
17540         خورد  0.866735
49307           یخ  0.860600
17008          خشک  0.851395
44576        کاملا  0.841558
27748          عدد  0.830023
17975    خیلی خیلی  0.818706
8234          بدون  0.816601
26814         ضعیف  0.806458
9862           بعد  0.796501
8074          بدتر  0.790747
25186        سیگار  0.784403
27809          عدم  0.780525
12685          بوی  0.774994
28160          غذا  0.770298
13536        تاخیر  0.760698

In [25]:
# get new text to find label
new_comment = input("Enter Comment : ")
best_estimator.predict([new_comment])

array([1], dtype=int64)

In [ ]:
# another way ai suggested

In [ ]:
# ===== COMPLETE FIXED CODE =====
import re
import numpy as np
import pandas as pd
from parsivar import Tokenizer, Normalizer
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import GridSearchCV, StratifiedKFold, cross_val_score
from sklearn.svm import LinearSVC
from sklearn.metrics import classification_report

# ===== Load Data =====
train_df = pd.read_csv('train.csv', delimiter="\t")
X = train_df['comment']
y = train_df['label_id']

# ===== Load Stopwords =====
with open('stopwords.dat', 'rt', encoding='UTF-8') as file:
    stopwords = file.read().splitlines()

# ===== Initialize Tools =====
normalizer = Normalizer()
my_tokenizer = Tokenizer()

# ===== Preprocess =====
def preprocess(text):
    text = normalizer.normalize(text)
    text = re.sub(r'[^\w\s\u0600-\u06FF]', ' ', text)
    text = re.sub(r"\u200c", " ", text)
    text = re.sub(r'[؟،؛٪]', ' ', text)
    text = re.sub(r"(.)\1{2,}", r"\1", text)
    text = re.sub(r"\s+", " ", text).strip()
    tokens = my_tokenizer.tokenize_words(text)
    text = [w for w in tokens if w not in stopwords]
    return " ".join(text) if len(text) > 0 else " "

# ===== Clean Data ONCE =====
X_clean = X.apply(preprocess)

# ===== Replace empty strings with space =====
X_clean = X_clean.replace('', ' ')
X_clean = X_clean.fillna(' ')

# ===== Test Pipeline =====
pipeline = Pipeline([
    ('tfidf', TfidfVectorizer(max_features=5000, min_df=1, max_df=1.0)),
    ('Classifier', LinearSVC(C=1))
])

scores = cross_val_score(pipeline, X_clean, y, cv=3, scoring='f1_macro')
print("Test scores:", scores)
print("Mean:", scores.mean())

# ===== If works, run GridSearch =====
if scores.mean() > 0:
    param_grid = {
        "tfidf__ngram_range": [(1, 1), (1, 2)],
        "tfidf__min_df": [1, 3, 5],
        "tfidf__max_df": [0.8, 0.95, 1.0],
        "Classifier__C": [0.1, 1, 10]
    }

    skf = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)

    grid = GridSearchCV(
        pipeline, param_grid, scoring='f1_macro', cv=skf, verbose=2, n_jobs=-1
    )
    grid.fit(X_clean, y)

    print("\nBest params:", grid.best_params_)
    print("Best score:", grid.best_score_)
else:
    print("❌ Pipeline failed!")

Test scores: [0.80889853 0.81460576 0.80948206]
Mean: 0.8109954507812395
Fitting 3 folds for each of 54 candidates, totalling 162 fits