# Session 8

Types of scaler (StandardScaler, MinMaxScaler) - Work with text : Encode texts (OneHot, LabeleEncoder)-Text Vectorizer (CountVectorize, TF-IDF) -
pre_processing on texts : Normalizer, Tokenizer, Stemming, Stopword remover (work with Parsivar (biult on nltk))-Recommender system

## Scalers

In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [2]:
#StandardScaler min-->0 std--> 1
score1 = np.array([1,2.5,3,5]).reshape(-1,1)
score2 = np.array([12,17,9,20]).reshape(-1,1)
score3 = np.array([20,50,100,74]).reshape(-1,1)

scaler = StandardScaler()
score_new=scaler.fit_transform(score1)
score_new

#Inverse
scaler.inverse_transform(score_new)

array([[1. ],
       [2.5],
       [3. ],
       [5. ]])

In [3]:
#MinMax
scaler = MinMaxScaler(feature_range=(0,100)) #range you want
scaler.fit([[9],[20]]) #min and max of your list must be detrmined
scaler.transform(score2)

array([[ 27.27272727],
       [ 72.72727273],
       [  0.        ],
       [100.        ]])

In [4]:
#Inverse
scaler.inverse_transform([[90]])

array([[18.9]])

## Text Vectorize and Encoding

OneHotEncoder:     Gender → Male=1/Female=0 

LabelEncoder:      Gender → Male=1, Female=0 (single column)

CountVectorizer:   Text → word counts (bag of words)

All are encoders — just for different data types!

In [5]:
name = np.array(['mobile','speaker','mobile','headset','speaker'])

In [6]:
#LabelEncoder
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
encoder = LabelEncoder()
encoder.fit_transform(name)

array([1, 2, 1, 0, 2], dtype=int64)

In [7]:
#OneHot
encoder = OneHotEncoder()
result=encoder.fit_transform(name.reshape(-1,1))
print(result.toarray())
#Each name = one column
#Value = 1 if matches, 0 if not
#→ "Is this Ali? Yes/No"

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]

In [8]:
#Countvectorize
from sklearn.feature_extraction.text import CountVectorizer

In [9]:
name = np.array(['mobile mobile','speaker','mobile','headset','speaker'])
vectorize = CountVectorizer()
vectorize.fit_transform(name)

#take the encodes with vocab_
print(vectorize.vocabulary_)

#get the unique 
print(vectorize.get_feature_names_out())
vectorize.fit_transform(name).toarray()

{'mobile': 1, 'speaker': 2, 'headset': 0}
['headset' 'mobile' 'speaker']

array([[0, 2, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [0, 0, 1]], dtype=int64)

In [10]:
#onehot is for words - countvectorize for text
#Example in text
from sklearn.feature_extraction.text import CountVectorizer

docs = ['cat dog cat', 'dog bird']

vectorizer = CountVectorizer()
result = vectorizer.fit_transform(docs)

#          bird  cat  dog
# Doc 1:  [0,   2,   1]   ← 2 cats, 1 dog, 0 birds
# Doc 2:  [1,   0,   1]   ← 1 bird, 0 cats, 1 dog
result.toarray()

array([[0, 2, 1],
       [1, 0, 1]], dtype=int64)

In [11]:
vec2 = CountVectorizer()
vec2.fit_transform([docs[0]])

<1x2 sparse matrix of type '<class 'numpy.int64'>'
	with 2 stored elements in Compressed Sparse Row format>

CountVectorizer: "cat" appears 5 times → score = 5

TF-IDF:          "cat" appears 5 times, BUT "cat" appears in EVERY document
                  → score = LOW (common word = not important)

                 "python" appears 2 times, BUT only in 1 document
                  → score = HIGH (rare word = very important!)


                  TF-IDF = TF × IDF

TF (Term Frequency)        = How often word appears in THIS document
IDF (Inverse Document Freq) = How RARE the word is across ALL documents

In [12]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
vectorizer.fit_transform(name).toarray()
print(vectorize.get_feature_names_out())
vectorize.vocabulary_

['headset' 'mobile' 'speaker']

{'mobile': 1, 'speaker': 2, 'headset': 0}

In [13]:
docs = ['cat dog cat', 'dog bird']

vectorizer = TfidfVectorizer()
result = vectorizer.fit_transform(docs)

result.toarray()

array([[0.        , 0.94215562, 0.33517574],
       [0.81480247, 0.        , 0.57973867]])

In [14]:
CountVectorizer:                    TF-IDF:
          bird  cat  dog                  bird   cat   dog
Doc 1:  [  0,    2,   1 ]         Doc 1: [0.00, 0.88, 0.38]
Doc 2:  [  1,    0,   1 ]         Doc 2: [0.65, 0.00, 0.65]

CountVectorizer:                   TF-IDF:
  "cat"=2 (raw count)               "cat"=0.88 (high importance —
                                   appears twice but only in 1 doc!)
  "dog"=1 in both docs              "dog"=0.38 (low importance —
                                   appears in BOTH docs — common word)

SyntaxError: invalid character '—' (U+2014) (1620205545.py, line 7)

### Text Pre_processing

In [15]:
from parsivar import Tokenizer, Normalizer
tokenizer = Tokenizer()
normalizer= Normalizer()

In [16]:
punctuation_list= "!@#$%^,،؟?،"
import re
def pre_processing(text):
    text = normalizer.normalize(text)
    text = re.sub(r'(.)\1{2,}', r'\1', text)
    text = "".join([char for char in text if char not in punctuation_list])
    tokens = tokenizer.tokenize_words(text)
    return text, tokens

pre_processing('سلاااام، چه طورییییی؟')

('سلام  چه طوری ', ['سلام', 'چه', 'طوری'])

In [17]:
#ُsentences tokenize
text = 'سلاااام، چه طورییییی؟.من که عالیم مرسییی'
tokens = tokenizer.tokenize_sentences(text)

text = ([char for char in text if char not in punctuation_list])
tokens
"".join(text)

'سلاااام چه طورییییی.من که عالیم مرسییی'

In [18]:
# Stemming
from parsivar import FindStems

stemmer = FindStems()
print(stemmer.convert_to_stem('کتابی'))
print(stemmer.convert_to_stem('کتاب های'))
print(stemmer.convert_to_stem('کتاب '))

print(stemmer.convert_to_stem('میخوانم'))
print(stemmer.convert_to_stem('میخوانیم'))

کتاب
کتاب
کتاب
خواند&خوان
خواند&خوان

## Recmmonder System

In [19]:
# IMBD Data
df = pd.read_csv("imdb_top_1000.csv")
df

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,https://m.media-amazon.com/images/M/MV5BNGEwMT...,Breakfast at Tiffany's,1961,A,115 min,"Comedy, Drama, Romance",7.6,A young New York socialite becomes interested ...,76.0,Blake Edwards,Audrey Hepburn,George Peppard,Patricia Neal,Buddy Ebsen,166544,NaN
996,https://m.media-amazon.com/images/M/MV5BODk3Yj...,Giant,1956,G,201 min,"Drama, Western",7.6,Sprawling epic covering the life of a Texas ca...,84.0,George Stevens,Elizabeth Taylor,Rock Hudson,James Dean,Carroll Baker,34075,NaN
997,https://m.media-amazon.com/images/M/MV5BM2U3Yz...,From Here to Eternity,1953,Passed,118 min,"Drama, Romance, War",7.6,"In Hawaii in 1941, a private is cruelly punish...",85.0,Fred Zinnemann,Burt Lancaster,Montgomery Clift,Deborah Kerr,Donna Reed,43374,"30,500,000"
998,https://m.media-amazon.com/images/M/MV5BZTBmMj...,Lifeboat,1944,NaN,97 min,"Drama, War",7.6,Several survivors of a torpedoed merchant ship...,78.0,Alfred Hitchcock,Tallulah Bankhead,John Hodiak,Walter Slezak,William Bendix,26471,NaN
999,https://m.media-amazon.com/images/M/MV5BMTY5OD...,The 39 Steps,1935,NaN,86 min,"Crime, Mystery, Thriller",7.6,A man in London tries to help a counter-espion...,93.0,Alfred Hitchcock,Robert Donat,Madeleine Carroll,Lucie Mannheim,Godfrey Tearle,51853,NaN

In [20]:
import os
os.getcwd()

'D:\\ML Course\\Mesbah\\Session 8'

In [21]:
#Drop columns you do not need - has no effect on the RS
df.drop(columns=['Poster_Link','Released_Year','Certificate','Runtime','IMDB_Rating','Overview','Meta_score','No_of_Votes','Gross'])

,Series_Title,Genre,Director,Star1,Star2,Star3,Star4
0,The Shawshank Redemption,Drama,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler
1,The Godfather,"Crime, Drama",Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton
2,The Dark Knight,"Action, Crime, Drama",Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine
3,The Godfather: Part II,"Crime, Drama",Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton
4,12 Angry Men,"Crime, Drama",Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler
...,...,...,...,...,...,...,...
995,Breakfast at Tiffany's,"Comedy, Drama, Romance",Blake Edwards,Audrey Hepburn,George Peppard,Patricia Neal,Buddy Ebsen
996,Giant,"Drama, Western",George Stevens,Elizabeth Taylor,Rock Hudson,James Dean,Carroll Baker
997,From Here to Eternity,"Drama, Romance, War",Fred Zinnemann,Burt Lancaster,Montgomery Clift,Deborah Kerr,Donna Reed
998,Lifeboat,"Drama, War",Alfred Hitchcock,Tallulah Bankhead,John Hodiak,Walter Slezak,William Bendix
999,The 39 Steps,"Crime, Mystery, Thriller",Alfred Hitchcock,Robert Donat,Madeleine Carroll,Lucie Mannheim,Godfrey Tearle

In [22]:
#make a new columns including all features
df["combine"] = df["Series_Title"] + " " + df['Genre'] + " " +df['Director'] + " "+ df['Star1'] + " " + df["Star2"] + " " + df['Star3'] + " "+ df["Star4"]  
df["combine"][0]

'The Shawshank Redemption Drama Frank Darabont Tim Robbins Morgan Freeman Bob Gunton William Sadler'

In [23]:
vectorize = CountVectorizer()
vectorize.fit(df['combine'])

vectorize.transform([df["combine"][0]])

<1x5817 sparse matrix of type '<class 'numpy.int64'>'
	with 14 stored elements in Compressed Sparse Row format>

In [24]:
#'The Shawshank Redemption Drama Frank Darabont Tim Robbins Morgan Freeman Bob Gunton William Sadler'

#problem Frank Darabont are consider as two person not one
df["combine"] = (df["Series_Title"].str.replace(" ", "_") + " " + 
                 df['Genre'].str.replace(",", "") + " " + 
                 df['Director'].str.replace(" ", "_") + " " +
                 df['Star1'].str.replace(" ", "_") + " " + 
                 df["Star2"].str.replace(" ", "_") + " " + 
                 df['Star3'].str.replace(" ", "_") + " " +
                 df["Star4"].str.replace(" ", "_"))

df["combine"][2]

'The_Dark_Knight Action Crime Drama Christopher_Nolan Christian_Bale Heath_Ledger Aaron_Eckhart Michael_Caine'

In [25]:
# All
vectorize = CountVectorizer()
vectorize.fit(df['combine'])
vectorize.transform(df["combine"])
print(vectorize.get_feature_names_out())
vectorize.vocabulary_

vectorize.transform(df["combine"])

['10_to_yuma' '12_angry_men' '12_years_a_slave' ...
 'ôkami_kodomo_no_ame_to_yuki' 'ömer_faruk_sorak' 'özge_özberk']

<1000x4490 sparse matrix of type '<class 'numpy.int64'>'
	with 8970 stored elements in Compressed Sparse Row format>

In [26]:
# how it wroks : first code each unique words then make a matrix and count them - each rwo is a document and each columns is a unique word
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd

# دو سند با کلمات مشترک
documents = [
    "apple banana apple orange",      # سند 1: سیب ۲ بار، موز ۱ بار، پرتقال ۱ بار
    "apple banana banana grape"       # سند 2: سیب ۱ بار، موز ۲ بار، انگور ۱ بار
]

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(documents)
print(X.toarray())
print(vectorizer.vocabulary_)

[[2 1 0 1]
 [1 2 1 0]]
{'apple': 0, 'banana': 1, 'orange': 3, 'grape': 2}

In [27]:
# Similarity 
from sklearn.neighbors import NearestNeighbors
from sklearn.metrics.pairwise import cosine_similarity

In [48]:
df = pd.read_csv("imdb_top_1000.csv")

df2=df.drop(columns=['Poster_Link','Released_Year','Certificate','Runtime','IMDB_Rating','Overview','Meta_score','No_of_Votes','Gross'])

df2["combine"] = (df["Series_Title"].str.replace(" ", "_") + " " + 
                 df['Genre'].str.replace(",", "") + " " + 
                 df['Director'].str.replace(" ", "_") + " " +
                 df['Star1'].str.replace(" ", "_") + " " + 
                 df["Star2"].str.replace(" ", "_") + " " + 
                 df['Star3'].str.replace(" ", "_") + " " +
                 df["Star4"].str.replace(" ", "_"))

vectorizer = CountVectorizer()
vectorizer.fit(df2['combine'])
result=vectorizer.transform(df2["combine"])

result.toarray()
vectorizer.get_feature_names_out()
print(vectorizer.vocabulary_)

{'the_shawshank_redemption': 4050, 'drama': 1152, 'frank_darabont': 1376, 'tim_robbins': 4115, 'morgan_freeman': 2912, 'bob_gunton': 631, 'william_sadler': 4368, 'the_godfather': 3966, 'crime': 929, 'francis_ford_coppola': 1370, 'marlon_brando': 2680, 'al_pacino': 248, 'james_caan': 1843, 'diane_keaton': 1084, 'the_dark_knight': 3946, 'action': 202, 'christopher_nolan': 872, 'christian_bale': 854, 'heath_ledger': 1638, 'aaron_eckhart': 189, 'michael_caine': 2790, '_part_ii': 118, 'robert_de_niro': 3409, 'robert_duvall': 3412, '12_angry_men': 1, 'sidney_lumet': 3715, 'henry_fonda': 1657, 'lee_j': 2435, '_cobb': 41, 'martin_balsam': 2684, 'john_fiedler': 2050, 'the_lord_of_the_rings': 4010, '_the_return_of_the_king': 152, 'adventure': 217, 'peter_jackson': 3189, 'elijah_wood': 1219, 'viggo_mortensen': 4264, 'ian_mckellen': 1739, 'orlando_bloom': 3084, 'pulp_fiction': 3255, 'quentin_tarantino': 3261, 'john_travolta': 2097, 'uma_thurman': 4224, 'samuel_l': 3585, '_jackson': 83, 'bruce_willis': 705, 'schindler': 3620, 's_list': 3538, 'biography': 604, 'history': 1683, 'steven_spielberg': 3816, 'liam_neeson': 2484, 'ralph_fiennes': 3289, 'ben_kingsley': 563, 'caroline_goodall': 763, 'inception': 1764, 'sci': 3621, 'fi': 1337, 'leonardo_dicaprio': 2460, 'joseph_gordon': 2132, 'levitt': 2476, 'elliot_page': 1234, 'ken_watanabe': 2285, 'fight_club': 1339, 'david_fincher': 1011, 'brad_pitt': 660, 'edward_norton': 1193, 'meat_loaf': 2754, 'zach_grenier': 4455, '_the_fellowship_of_the_ring': 149, 'sean_bean': 3632, 'forrest_gump': 1362, 'romance': 3462, 'robert_zemeckis': 3433, 'tom_hanks': 4142, 'robin_wright': 3438, 'gary_sinise': 1432, 'sally_field': 3564, 'il_buono': 1750, '_il_brutto': 73, '_il_cattivo': 74, 'western': 4334, 'sergio_leone': 3655, 'clint_eastwood': 900, 'eli_wallach': 1216, 'lee_van_cleef': 2442, 'aldo_giuffrè': 267, '_the_two_towers': 157, 'the_matrix': 4022, 'lana_wachowski': 2397, 'lilly_wachowski': 2496, 'keanu_reeves': 2268, 'laurence_fishburne': 2415, 'carrie': 764, 'anne_moss': 411, 'goodfellas': 1535, 'martin_scorsese': 2692, 'ray_liotta': 3315, 'joe_pesci': 2021, 'lorraine_bracco': 2531, 'star_wars': 3791, '_episode_v_': 56, '_the_empire_strikes_back': 147, 'fantasy': 1313, 'irvin_kershner': 1785, 'mark_hamill': 2668, 'harrison_ford': 1615, 'carrie_fisher': 765, 'billy_dee_williams': 599, 'one_flew_over_the_cuckoo': 3078, 's_nest': 3540, 'milos_forman': 2860, 'jack_nicholson': 1818, 'louise_fletcher': 2543, 'michael_berryman': 2788, 'peter_brocco': 3183, 'hamilton': 1602, 'thomas_kail': 4095, 'lin': 2498, 'manuel_miranda': 2622, 'phillipa_soo': 3209, 'leslie_odom_jr': 2471, 'renée_elise_goldsberry': 3341, 'gisaengchung': 1507, 'comedy': 910, 'thriller': 4105, 'bong_joon_ho': 643, 'kang': 2224, 'ho_song': 1688, 'lee_sun': 2439, 'kyun': 2365, 'cho_yeo': 837, 'jeong': 1959, 'choi_woo': 839, 'sik': 3720, 'soorarai_pottru': 3755, 'sudha_kongara': 3823, 'suriya': 3836, 'madhavan': 2587, 'paresh_rawal': 3112, 'aparna_balamurali': 445, 'interstellar': 1777, 'matthew_mcconaughey': 2733, 'anne_hathaway': 409, 'jessica_chastain': 1974, 'mackenzie_foy': 2578, 'cidade_de_deus': 881, 'fernando_meirelles': 1333, 'kátia_lund': 2368, 'alexandre_rodrigues': 291, 'leandro_firmino': 2432, 'matheus_nachtergaele': 2722, 'sen_to_chihiro_no_kamikakushi': 3645, 'animation': 392, 'family': 1308, 'hayao_miyazaki': 1635, 'daveigh_chase': 1005, 'suzanne_pleshette': 3843, 'miyu_irino': 2887, 'rumi_hiiragi': 3497, 'saving_private_ryan': 3613, 'war': 4317, 'matt_damon': 2725, 'tom_sizemore': 4151, 'edward_burns': 1188, 'the_green_mile': 3974, 'michael_clarke_duncan': 2792, 'david_morse': 1022, 'bonnie_hunt': 646, 'la_vita_è_bella': 2389, 'roberto_benigni': 3435, 'nicoletta_braschi': 2996, 'giorgio_cantarini': 1505, 'giustino_durano': 1511, 'se7en': 3628, 'mystery': 2935, 'kevin_spacey': 2302, 'andrew_kevin_walker': 365, 'the_silence_of_the_lambs': 4053, 'jonathan_demme': 2117, 'jodie_foster': 2016, 'anthony_hopkins': 425, 'lawrence_a': 2418, '_bonney': 31, 'kasi_lemmons': 2241, 'george_lucas': 1466, 'alec_guinness': 271, 'seppuku': 3649, 'masaki_kobayashi': 2717, 'tatsuya_nakadai': 3885, 'akira_ishihama': 241, 'shima_iwashita': 3689, 'tetsurô_tanba': 3915, 'shichinin_no_samurai': 3685, 'akira_kurosawa': 242, 'toshirô_mifune': 4178, 'takashi_shimura': 3862, 'keiko_tsushima': 2271, 'yukiko_shimazaki': 4434, 'it': 1798, 's_a_wonderful_life': 3525, 'frank_capra': 1375, 'james_stewart': 1869, 'donna_reed': 1135, 'lionel_barrymore': 2509, 'thomas_mitchell': 4098, 'joker': 2107, 'todd_phillips': 4133, 'joaquin_phoenix': 2013, 'zazie_beetz': 4464, 'frances_conroy': 1365, 'whiplash': 4340, 'music': 2925, 'damien_chazelle': 952, 'miles_teller': 2855, '_simmons': 134, 'melissa_benoist': 2768, 'paul_reiser': 3150, 'the_intouchables': 3986, 'olivier_nakache': 3064, 'éric_toledano': 4486, 'françois_cluzet': 1394, 'omar_sy': 3066, 'anne_le_ny': 410, 'the_prestige': 4037, 'hugh_jackman': 1712, 'scarlett_johansson': 3617, 'the_departed': 3951, 'mark_wahlberg': 2676, 'the_pianist': 4036, 'roman_polanski': 3461, 'adrien_brody': 216, 'thomas_kretschmann': 4096, 'frank_finlay': 1377, 'emilia_fox': 1243, 'gladiator': 1513, 'ridley_scott': 3387, 'russell_crowe': 3506, 'connie_nielsen': 912, 'oliver_reed': 3056, 'american_history_x': 323, 'tony_kaye': 4169, 'edward_furlong': 1190, 'beverly_d': 579, 'angelo': 388, 'jennifer_lien': 1954, 'the_usual_suspects': 4073, 'bryan_singer': 710, 'gabriel_byrne': 1414, 'chazz_palminteri': 821, 'stephen_baldwin': 3796, 'léon': 2570, 'luc_besson': 2550, 'jean_reno': 1925, 'gary_oldman': 1431, 'natalie_portman': 2960, 'danny_aiello': 979, 'the_lion_king': 4005, 'roger_allers': 3449, 'rob_minkoff': 3399, 'matthew_broderick': 2729, 'jeremy_irons': 1961, 'james_earl_jones': 1850, 'terminator_2': 3905, '_judgment_day': 85, 'james_cameron': 1845, 'arnold_schwarzenegger': 461, 'linda_hamilton': 2502, 'robert_patrick': 3420, 'nuovo_cinema_paradiso': 3037, 'giuseppe_tornatore': 1510, 'philippe_noiret': 3207, 'enzo_cannavale': 1266, 'antonella_attili': 434, 'isa_danieli': 1788, 'hotaru_no_haka': 1698, 'isao_takahata': 1793, 'tsutomu_tatsumi': 4200, 'ayano_shiraishi': 498, 'akemi_yamaguchi': 236, 'yoshiko_shinohara': 4428, 'back_to_the_future': 511, 'michael_j': 2799, '_fox': 64, 'christopher_lloyd': 868, 'lea_thompson': 2431, 'crispin_glover': 931, 'once_upon_a_time_in_the_west': 3075, 'charles_bronson': 800, 'claudia_cardinale': 895, 'jason_robards': 1907, 'psycho': 3254, 'horror': 1696, 'alfred_hitchcock': 297, 'anthony_perkins': 427, 'janet_leigh': 1893, 'vera_miles': 4245, 'john_gavin': 2056, 'casablanca': 773, 'michael_curtiz': 2793, 'humphrey_bogart': 1718, 'ingrid_bergman': 1771, 'paul_henreid': 3140, 'claude_rains': 893, 'modern_times': 2890, 'charles_chaplin': 801, 'paulette_goddard': 3158, 'henry_bergman': 1655, 'tiny_sandford': 4122, 'city_lights': 885, 'virginia_cherrill': 4281, 'florence_lee': 1353, 'harry_myers': 1620, 'capharnaüm': 742, 'nadine_labaki': 2944, 'zain_al_rafeea': 4460, 'yordanos_shiferaw': 4424, 'boluwatife_treasure_bankole': 640, 'kawsar_al_haddad': 2260, 'ayla': 501, '_the_daughter_of_war': 145, 'can_ulkay': 739, 'erdem_can': 1269, 'çetin_tekindor': 4484, 'ismail_hacioglu': 1795, 'kyung': 2366, 'jin_lee': 1998, 'vikram_vedha': 4269, 'gayatri': 1443, 'pushkar': 3257, 'vijay_sethupathi': 4266, 'shraddha_srinath': 3704, 'kimi_no_na_wa': 2321, 'makoto_shinkai': 2604, 'ryûnosuke_kamiki': 3524, 'mone_kamishiraishi': 2900, 'ryô_narita': 3522, 'aoi_yûki': 444, 'dangal': 964, 'nitesh_tiwari': 3013, 'aamir_khan': 188, 'sakshi_tanwar': 3559, 'fatima_sana_shaikh': 1320, 'sanya_malhotra': 3596, 'spider': 3766, 'man': 2612, '_into_the_spider': 81, 'verse': 4249, 'bob_persichetti': 634, 'peter_ramsey': 3194, 'rodney_rothman': 3446, 'shameik_moore': 3670, 'jake_johnson': 1840, 'avengers': 493, '_endgame': 55, 'anthony_russo': 429, 'joe_russo': 2022, 'robert_downey_jr': 3411, 'chris_evans': 843, 'mark_ruffalo': 2672, '_infinity_war': 80, 'chris_hemsworth': 844, 'coco': 904, 'lee_unkrich': 2441, 'adrian_molina': 215, 'anthony_gonzalez': 423, 'gael_garcía_bernal': 1418, 'benjamin_bratt': 569, 'django_unchained': 1108, 'jamie_foxx': 1876, 'christoph_waltz': 861, 'kerry_washington': 2291, 'the_dark_knight_rises': 3947, 'tom_hardy': 4143, '3_idiots': 9, 'rajkumar_hirani': 3283, 'mona_singh': 2899, 'sharman_joshi': 3674, 'taare_zameen_par': 3854, 'amole_gupte': 332, 'darsheel_safary': 995, 'tisca_chopra': 4124, 'wall': 4305, 'andrew_stanton': 372, 'ben_burtt': 558, 'elissa_knight': 1221, 'jeff_garlin': 1940, 'fred_willard': 1399, 'the_lives_of_others': 4007, 'florian_henckel_von_donnersmarck': 1355, 'ulrich_mühe': 4221, 'martina_gedeck': 2696, 'sebastian_koch': 3640, 'ulrich_tukur': 4223, 'oldeuboi': 3051, 'chan': 797, 'wook_park': 4394, 'choi_min': 838, 'yoo_ji': 4423, 'tae': 3856, 'kang_hye': 2225, 'kim_byeong': 2310, 'ok': 3047, 'memento': 2772, 'guy_pearce': 1577, 'joe_pantoliano': 2020, 'mark_boone_junior': 2667, 'mononoke': 2904, 'hime': 1675, 'yôji_matsuda': 4444, 'yuriko_ishida': 4440, 'yûko_tanaka': 4450, 'billy_crudup': 597, 'once_upon_a_time_in_america': 3074, 'james_woods': 1872, 'elizabeth_mcgovern': 1227, 'treat_williams': 4188, 'raiders_of_the_lost_ark': 3275, 'karen_allen': 2232, 'paul_freeman': 3136, 'john_rhys': 2087, 'davies': 1031, 'the_shining': 4051, 'stanley_kubrick': 3787, 'shelley_duvall': 3680, 'danny_lloyd': 986, 'scatman_crothers': 3618, 'apocalypse_now': 446, 'martin_sheen': 2693, 'frederic_forrest': 1401, 'alien': 302, 'sigourney_weaver': 3719, 'tom_skerritt': 4152, 'john_hurt': 2067, 'veronica_cartwright': 4248, 'anand': 346, 'musical': 2926, 'hrishikesh_mukherjee': 1704, 'rajesh_khanna': 3281, 'amitabh_bachchan': 330, 'sumita_sanyal': 3829, 'ramesh_deo': 3295, 'tengoku_to_jigoku': 3894, 'yutaka_sada': 4441, 'kyôko_kagawa': 2367, 'dr': 1151, '_strangelove_or': 138, '_how_i_learned_to_stop_worrying_and_love_the_bomb': 70, 'peter_sellers': 3195, 'george_c': 1461, '_scott': 133, 'sterling_hayden': 3807, 'keenan_wynn': 2269, 'witness_for_the_prosecution': 4378, 'billy_wilder': 601, 'tyrone_power': 4211, 'marlene_dietrich': 2679, 'charles_laughton': 805, 'elsa_lanchester': 1238, 'paths_of_glory': 3116, 'kirk_douglas': 2329, 'ralph_meeker': 3291, 'adolphe_menjou': 214, 'george_macready': 1468, 'rear_window': 3320, 'grace_kelly': 1540, 'wendell_corey': 4326, 'thelma_ritter': 4082, 'sunset_blvd': 3834, 'film': 1344, 'noir': 3020, 'william_holden': 4364, 'gloria_swanson': 1521, 'erich_von_stroheim': 1277, 'nancy_olson': 2950, 'the_great_dictator': 3972, 'jack_oakie': 1819, 'reginald_gardiner': 3328, '1917': 3, 'sam_mendes': 3570, 'dean': 1042, 'charles_chapman': 802, 'george_mackay': 1467, 'daniel_mays': 971, 'colin_firth': 908, 'tumbbad': 4204, 'rahi_anil_barve': 3274, 'anand_gandhi': 347, 'adesh_prasad': 210, 'sohum_shah': 3743, 'jyoti_malshe': 2202, 'andhadhun': 353, 'sriram_raghavan': 3775, 'ayushmann_khurrana': 502, 'tabu': 3855, 'radhika_apte': 3271, 'anil_dhawan': 391, 'drishyam': 1154, 'jeethu_joseph': 1935, 'mohanlal': 2893, 'meena': 2755, 'asha_sharath': 477, 'ansiba': 420, 'jagten': 1838, 'thomas_vinterberg': 4100, 'mads_mikkelsen': 2588, 'thomas_bo_larsen': 4092, 'annika_wedderkopp': 416, 'lasse_fogelstrøm': 2403, 'jodaeiye_nader_az_simin': 2014, 'asghar_farhadi': 475, 'payman_maadi': 3162, 'leila_hatami': 2445, 'sareh_bayat': 3608, 'shahab_hosseini': 3667, 'incendies': 1763, 'denis_villeneuve': 1061, 'lubna_azabal': 2549, 'mélissa_désormeaux': 2940, 'poulin': 3236, 'maxim_gaudette': 2745, 'mustafa_kamel': 2927, 'miracle_in_cell_no': 2870, 'mehmet_ada_öztekin': 2762, 'aras_bulut_iynemli': 449, 'nisa_sofiya_aksongur': 3011, 'deniz_baysal': 1062, 'celile_toyon_uysal': 793, 'babam_ve_oglum': 507, 'çagan_irmak': 4483, 'fikret_kuskan': 1340, 'hümeyra': 1732, 'ege_tanman': 1198, 'inglourious_basterds': 1769, 'diane_kruger': 1085, 'eli_roth': 1215, 'mélanie_laurent': 2938, 'eternal_sunshine_of_the_spotless_mind': 1287, 'michel_gondry': 2822, 'jim_carrey': 1985, 'kate_winslet': 2247, 'tom_wilkinson': 4155, 'gerry_robert_byrne': 1490, 'amélie': 341, 'jean': 1919, 'pierre_jeunet': 3218, 'audrey_tautou': 486, 'mathieu_kassovitz': 2724, 'rufus': 3495, 'lorella_cravotta': 2529, 'snatch': 3740, 'guy_ritchie': 1578, 'jason_statham': 1910, 'benicio_del_toro': 568, 'dennis_farina': 1064, 'requiem_for_a_dream': 3344, 'darren_aronofsky': 992, 'ellen_burstyn': 1230, 'jared_leto': 1899, 'jennifer_connelly': 1949, 'marlon_wayans': 2681, 'american_beauty': 321, 'annette_bening': 412, 'thora_birch': 4103, 'wes_bentley': 4332, 'good_will_hunting': 1534, 'gus_van_sant': 1571, 'robin_williams': 3437, 'ben_affleck': 557, 'stellan_skarsgård': 3795, 'bacheha': 510, 'ye_aseman': 4412, 'sport': 3770, 'majid_majidi': 2601, 'mohammad_amir_naji': 2891, 'amir_farrokh_hashemian': 326, 'bahare_seddiqi': 517, 'nafise_jafar': 2945, 'mohammadi': 2892, 'toy_story': 4181, 'john_lasseter': 2070, 'tim_allen': 4109, 'don_rickles': 1127, 'jim_varney': 1992, 'braveheart': 667, 'mel_gibson': 2764, 'sophie_marceau': 3757, 'patrick_mcgoohan': 3124, 'angus_macfadyen': 390, 'reservoir_dogs': 3345, 'harvey_keitel': 1631, 'tim_roth': 4116, 'michael_madsen': 2803, 'chris_penn': 847, 'full_metal_jacket': 1411, 'matthew_modine': 2734, '_lee_ermey': 91, 'vincent_d': 4275, 'onofrio': 3080, 'adam_baldwin': 203, 'idi_i_smotri': 1745, 'elem_klimov': 1210, 'aleksey_kravchenko': 278, 'olga_mironova': 3054, 'liubomiras_laucevicius': 2516, 'vladas_bagdonas': 4291, 'aliens': 303, 'michael_biehn': 2789, 'carrie_henn': 766, 'amadeus': 318, '_murray_abraham': 105, 'tom_hulce': 4147, 'elizabeth_berridge': 1225, 'roy_dotrice': 3488, 'scarface': 3616, 'brian_de_palma': 676, 'michelle_pfeiffer': 2830, 'steven_bauer': 3814, 'mary_elizabeth_mastrantonio': 2701, '_episode_vi_': 57, '_return_of_the_jedi': 126, 'richard_marquand': 3379, 'das_boot': 998, 'wolfgang_petersen': 4383, 'jürgen_prochnow': 2205, 'herbert_grönemeyer': 1665, 'klaus_wennemann': 2340, 'hubertus_bengsch': 1707, 'taxi_driver': 3887, 'cybill_shepherd': 940, 'albert_brooks': 263, 'the_sting': 4058, 'george_roy_hill': 1474, 'paul_newman': 3148, 'robert_redford': 3421, 'robert_shaw': 3426, 'charles_durning': 803, 'a_clockwork_orange': 178, 'malcolm_mcdowell': 2605, 'patrick_magee': 3123, 'michael_bates': 2786, 'warren_clarke': 4320, '2001': 4, '_a_space_odyssey': 19, 'keir_dullea': 2273, 'gary_lockwood': 1430, 'william_sylvester': 4370, 'daniel_richter': 975, 'per_qualche_dollaro_in_più': 3170, 'gian_maria_volontè': 1494, 'mara_krupp': 2625, 'lawrence_of_arabia': 2419, 'david_lean': 1016, 'peter_o': 3192, 'toole': 4175, 'anthony_quinn': 428, 'jack_hawkins': 1814, 'the_apartment': 3921, 'jack_lemmon': 1816, 'shirley_maclaine': 3697, 'fred_macmurray': 1398, 'ray_walston': 3318, 'north_by_northwest': 3031, 'cary_grant': 771, 'eva_marie_saint': 1294, 'james_mason': 1863, 'jessie_royce_landis': 1978, 'vertigo': 4250, 'kim_novak': 2314, 'barbara_bel_geddes': 523, 'tom_helmore': 4144, 'singin': 3728, '_in_the_rain': 77, 'stanley_donen': 3784, 'gene_kelly': 1452, 'donald_o': 1130, 'connor': 913, 'debbie_reynolds': 1047, 'ikiru': 1748, 'nobuo_kaneko': 3019, 'shin': 3691, 'ichi_himori': 1741, 'haruo_tanaka': 1629, 'ladri_di_biciclette': 2390, 'vittorio_de_sica': 4285, 'lamberto_maggiorani': 2396, 'enzo_staiola': 1267, 'lianella_carell': 2485, 'elena_altieri': 1211, 'double_indemnity': 1146, 'barbara_stanwyck': 525, 'edward_g': 1191, '_robinson': 127, 'byron_barr': 724, 'citizen_kane': 884, 'orson_welles': 3085, 'joseph_cotten': 2130, 'dorothy_comingore': 1143, 'agnes_moorehead': 223, 'm_': 2571, '_eine_stadt_sucht_einen_mörder': 53, 'fritz_lang': 1407, 'peter_lorre': 3190, 'ellen_widmann': 1233, 'inge_landgut': 1768, 'otto_wernicke': 3093, 'metropolis': 2781, 'brigitte_helm': 689, 'alfred_abel': 296, 'gustav_fröhlich': 1573, 'rudolf_klein': 3493, 'rogge': 3451, 'the_kid': 3991, 'edna_purviance': 1182, 'jackie_coogan': 1824, 'carl_miller': 749, 'chhichhore': 824, 'sushant_singh_rajput': 3840, 'shraddha_kapoor': 3703, 'varun_sharma': 4242, 'prateik': 3240, 'uri': 4232, '_the_surgical_strike': 156, 'aditya_dhar': 213, 'vicky_kaushal': 4254, 'mohit_raina': 2894, 'yami_gautam': 4404, '_chapter_1': 38, 'prashanth_neel': 3239, 'yash': 4406, 'srinidhi_shetty': 3774, 'ramachandra_raju': 3294, 'archana_jois': 451, 'green_book': 1548, 'peter_farrelly': 3187, 'mahershala_ali': 2597, 'linda_cardellini': 2501, 'sebastian_maniscalco': 3641, 'three_billboards_outside_ebbing': 4104, '_missouri': 102, 'martin_mcdonagh': 2689, 'frances_mcdormand': 1366, 'woody_harrelson': 4393, 'sam_rockwell': 3575, 'caleb_landry_jones': 734, 'talvar': 3872, 'meghna_gulzar': 2757, 'irrfan_khan': 1784, 'konkona_sen_sharma': 2347, 'neeraj_kabi': 2973, 'baahubali_2': 505, '_the_conclusion': 143, '_rajamouli': 123, 'prabhas': 3237, 'rana_daggubati': 3301, 'anushka_shetty': 442, 'tamannaah_bhatia': 3873, 'klaus': 2338, 'sergio_pablos': 3656, 'carlos_martínez_lópez': 758, 'jason_schwartzman': 1908, 'rashida_jones': 3310, 'nishikant_kamat': 3012, 'ajay_devgn': 233, 'shriya_saran': 3706, 'rajat_kapoor': 3279, 'queen': 3260, 'vikas_bahl': 4268, 'kangana_ranaut': 2226, 'rajkummar_rao': 3285, 'lisa_haydon': 2511, 'jeffrey_ho': 1942, 'mandariinid': 2616, 'zaza_urushadze': 4463, 'lembit_ulfsak': 2449, 'elmo_nüganen': 1236, 'giorgi_nakashidze': 1504, 'misha_meskhi': 2878, 'bhaag_milkha_bhaag': 580, 'rakeysh_omprakash_mehra': 3286, 'farhan_akhtar': 1315, 'sonam_kapoor': 3749, 'pawan_malhotra': 3161, 'art_malik': 466, 'gangs_of_wasseypur': 1422, 'anurag_kashyap': 440, 'manoj_bajpayee': 2621, 'richa_chadha': 3355, 'nawazuddin_siddiqui': 2968, 'tigmanshu_dhulia': 4106, 'udaan': 4216, 'vikramaditya_motwane': 4270, 'rajat_barmecha': 3278, 'ronit_roy': 3468, 'manjot_singh': 2620, 'ram_kapoor': 3293, 'paan_singh_tomar': 3097, 'mahie_gill': 2599, 'rajesh_abhay': 3280, 'hemendra_dandotiya': 1649, 'el_secreto_de_sus_ojos': 1205, 'juan_josé_campanella': 2156, 'ricardo_darín': 3352, 'soledad_villamil': 3746, 'pablo_rago': 3098, 'carla_quevedo': 754, 'warrior': 4322, 'gavin_o': 1442, 'nick_nolte': 2990, 'joel_edgerton': 2026, 'jennifer_morrison': 1955, 'shutter_island': 3707, 'emily_mortimer': 1247, 'up': 4231, 'pete_docter': 3178, 'bob_peterson': 635, 'edward_asner': 1187, 'jordan_nagai': 2124, 'john_ratzenberger': 2086, 'the_wolf_of_wall_street': 4079, 'jonah_hill': 2115, 'margot_robbie': 2644, 'chak_de': 796, '_india': 79, 'shimit_amin': 3690, 'shah_rukh_khan': 3666, 'vidya_malvade': 4263, 'sagarika_ghatge': 3555, 'shilpa_shukla': 3688, 'there_will_be_blood': 4085, 'paul_thomas_anderson': 3154, 'daniel_day': 968, 'lewis': 2478, 'paul_dano': 3134, 'ciarán_hinds': 880, 'martin_stringer': 2694, 'pan': 3103, 's_labyrinth': 3536, 'guillermo_del_toro': 1565, 'ivana_baquero': 1805, 'ariadna_gil': 453, 'sergi_lópez': 3654, 'maribel_verdú': 2650, 'toy_story_3': 4183, 'joan_cusack': 2008, 'ned_beatty': 2971, 'v_for_vendetta': 4233, 'james_mcteigue': 1865, 'hugo_weaving': 1717, 'rupert_graves': 3501, 'stephen_rea': 3803, 'rang_de_basanti': 3304, 'soha_ali_khan': 3742, 'siddharth': 3713, 'black': 611, 'sanjay_leela_bhansali': 3593, 'rani_mukerji': 3305, 'shernaz_patel': 3684, 'ayesha_kapoor': 500, 'batman_begins': 541, 'swades': 3844, '_we': 169, '_the_people': 151, 'ashutosh_gowariker': 479, 'gayatri_joshi': 1444, 'kishori_ballal': 2336, 'smit_sheth': 3738, 'der_untergang': 1072, 'oliver_hirschbiegel': 3055, 'bruno_ganz': 706, 'alexandra_maria_lara': 289, 'ulrich_matthes': 4220, 'juliane_köhler': 2176, 'hauru_no_ugoku_shiro': 1633, 'chieko_baishô': 828, 'takuya_kimura': 3869, 'tatsuya_gashûin': 3884, 'akihiro_miwa': 238, 'a_beautiful_mind': 175, 'ron_howard': 3465, 'ed_harris': 1169, 'christopher_plummer': 873, 'hera_pheri': 1663, 'priyadarshan': 3251, 'akshay_kumar': 244, 'sunil_shetty': 3831, 'lock': 2522, '_stock_and_two_smoking_barrels': 137, 'jason_flemyng': 1902, 'dexter_fletcher': 1080, 'nick_moran': 2989, '_confidential': 42, 'curtis_hanson': 938, 'kim_basinger': 2309,

In [49]:
# User use its movie to find realted ones
#user_movie = input("Your movie:")
user_movie = 'The Godfather'
user_movie_index = df2[df2['Series_Title']==user_movie]
user_movie_index.index[0]

1

In [50]:
user_movie_index.index

Index([1], dtype='int64')

In [51]:
user_movie_vector = result.toarray()[user_movie_index.index[0]]
user_movie_vector.shape
user_movie_vector

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [52]:
user_movie_vector = result.toarray()[user_movie_index.index[0]]
user_movie_vector.tolist()

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 ...]

In [53]:
vector = df2["combine"].iloc[user_movie_index.index[0]]
vectorizer.transform([vector]).toarray()

array([[0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [54]:
nearest_neighbors = NearestNeighbors(n_neighbors=5, metric='cosine', algorithm='brute')
nearest_neighbors.fit(result)

NearestNeighbors(algorithm='brute', metric='cosine')

In [55]:
#Explain cosine simi
a = [[0,0,1,1,0]]

b = [
     [0,0,1,1,0],
     [0,0,0,1,0],
     [0,1,1,1,0],
     [1,0,0,0,1]]
similiraties = cosine_similarity(a,b)
print(similiraties)

sorted_similarities = np.argsort(similiraties)
print(sorted_similarities.shape)

sorted_similarities = sorted_similarities[0][::-1]
sorted_similarities

[[1.         0.70710678 0.81649658 0.        ]]
(1, 4)

array([0, 2, 1, 3], dtype=int64)

In [61]:
#implement above on imbd
similiraties = cosine_similarity([user_movie_vector],result)
similiraties

sorted_similarities = np.argsort(similiraties)

sorted_similarities = sorted_similarities[0][::-1]
print(sorted_similarities)

similiraties.shape

[  1 974   3 108 484 416 823 849  74 809 164 523 305 447 485 670 398  71
 165 465 895 380 288 180 621 111 397  22 257 763 186 669 775 133 663 885
 356 888 649 893 232 896 218 112 774 639 901 782 791 384 802 103 630 622
 224 136 676 811 243 189 759 723 299 169 198 850 767 852 768 162 836 201
 153 696 695 147 693 687 332 680 335 163 505 611 577  55 953 954 450 958
 960 463  42 546 474 968 480  37  33 487  27 980 527  25 494 520 987  15
 989 519   6   4   2 512 949 222 597 921 922  87  86 424 603  77  79 931
 287 451 718 882 113 418 833 263 918 827 255  28 926 814 444 710 437 674
 308 442 345 132 584 938 664 261 762 375 441 241 123 607 533 653 438 939
 605 708 284 363 239 602 387 370 699 554 347 517 580 388 787 788 646 589
 619 383 274 742 285 682 280 572 439 302 336 254 636 491 432 443 720 765
 297 468   0 886 838 818  53 946 941 188  88  89  91 917 841 206 916  97
  98 122 883 881 154 880 141 200 868 981   9  20 652 128 360  17 121 364
 372 637 904 355 905  99 626  24  96 913  92 492 130  45 461 354 333 683
 869 996 138 344 671 504 667 998 349  11 662 661 350 352 658 656 403 404
  62 435 467  73 945 548 574  64 571 567 528 955 550 551 449 962 452 457
 459 937  40  76 585 613 489 408  34 413 970 471 928 601 328  80 423 933
 428 590 934 588 421 258 273 282 780 296 187 175 295 237 773 292 291 203
 289 817 731 735 182 784 196 278 276 195 184 250 824 269 268 825 747 748
 266 190 857 259 159 866 315 789 863 149 324 227 792 793 801 706 690 221
 689 322 440  56 434 225 445 197 508 248 496 497  57 191  67 501 215 252
 436 216 498 244 500  50  35 233 231 483 481  38 478 476  39 210 470 209
  31  41 466 229  46 490 235  30 464 238 207 211 204 240 212 455 454 495
  43 143 264 373 156 157 307 219 304 358 359 303 160 361 172 298 173 365
 117 310 311 312 139 327 326 334 142 140 338 340 131 342 137 134 323 314
 313 174 110 431 374 407 409 411 279  85 185  82 331 422 267 425 427 429
 265 430 283 181 400 386 107 377 105 104 294 385 176 179 293 391 392 290
 394  93 217 999 758 625 853 851 617 847 620 834 832 826 859 628 631 819
 813 812 805 635 858 860 586 877 884 593 879 594 595 878 598 873 862 600
 872 604 870 606 864 612 638 803 642 736 672 673 760 741 739 738 686 734
 795 732 729 728 697 726 713 701 668 766 769 770 790 643 644 786 647 648
 650 785 783 779 655 657 778 772 660 587 709 889 957 514 952 923 924 515
 925 990 518 975 929 930 979 988 524 555 940 983 553 951 549 986 529 985
 915 561 569 897 997 581 995 890 894 538 573 971 570 563 944 534 966 906
 909 977 993 910 964 911 541 978  21 247 234 764 281  18   7 306 301 300
 716 719 721   5  10 249 286 733  13 272 745 752 757  32 950 972 148  84
 846 167  90 161  94 152 150 705  36 867 871 898 874 116 124 125 126 845
 831 830 936 967 965 226 797 798 129 214 804  59  65 806 208 810 943 202
 942 821 144 509 453 351 610 381 353 659 684 462 703 486 614 552 665 575
 448 337 624 559 557 616 346 343 341 640 382 329 526 632 558 702 433 560
 513 579 317 629 654 319 545 414 412 521 472 460 525  54 102 556 100 794
 666  51 542 369  52 510 903 256 193 127 754 935 753 475 820 815  83 537
  26 390 536 253 228 251 402 908 236  19 246 907 641 608  68 260 379 199
 371 927 456 458 704 920 566 583 582 578 891 892 120 119 118 576 115 114
 568 899 919 900 109 902 106 565 101 446 564 912  95 562 914  81  63 932
  16 973 535 976  29 532 488 982 531  23 984 530 493 522 479  14  12 516
 502 991   8 503 992 511 994 506 507 482 969  78 469  75  72 547  70  69
  66 544 947 887 948  61  60  58 539 543 956 473  49  48  47 959 961  44
 963 540 477 591 155 592 743 271 270 744 746 749 750 751 677 262 755 756
 339 675 761 245 348 242 771 776 777 781 357 230 651 362 645 366 223 367
 678 679 220 275 309 707 700 711 712 316 714 318 715 717 320 321 722 724
 725 698 727 694 325 730 692 691 688 330 685 737 681 277 740 796 368 426
 171 848 168 618 166 399 854 855 401 856 158 615 861 405 406 151 609 410
 865 146 145 415 417 419 420 875 876 135 599 596 170 396 799 395 800 213
 376 634 807 378 808 205 633 816 822 194 192 627 828 829 389 623 835 183
 837 839 840 842 178 177 843 844 393 499]

(1, 1000)

In [37]:
n_recommend=4
recommended_result = sorted_similarities[1:1+n_recommend]
print(recommended_result)
df["Series_Title"].iloc[recommended_result]

[974   3 108 484]

974    The Godfather: Part III
3       The Godfather: Part II
108                   Scarface
484               The Irishman
Name: Series_Title, dtype: object

In [40]:
# whole code
# Recommender system:

user_movie = input("Your movie: ")
user_movie_index = df2[df2['Series_Title'] == user_movie]
user_movie_index = user_movie_index.index[0]
user_movie_vector = result.toarray()[user_movie_index]
similarities = cosine_similarity([user_movie_vector], result)
similarities

sorted_similarities = np.argsort(similarities)
sorted_similarities = sorted_similarities[0][::-1]
sorted_similarities

n_recommend = 4
recommended_result = sorted_similarities[1:1+n_recommend]
df["Series_Title"].iloc[recommended_result]

Your movie:  The Dark Knight

155            Batman Begins
774             3:10 to Yuma
36              The Prestige
63     The Dark Knight Rises
Name: Series_Title, dtype: object

In [41]:
sorted_similarities

array([  2, 155, 774,  36,  63, 356, 852, 953,  42, 850, 888, 577, 901,
       782, 968, 832, 573, 217, 663, 201,  55, 696, 768, 896, 224, 931,
       893, 345, 710, 674, 918, 308, 718, 375, 241, 605, 602, 763, 397,
       465, 130, 773, 257, 108, 928, 621,  71, 111, 165,   1, 485, 180,
        22, 784, 528, 380, 895, 288,  87, 759, 512, 885, 505, 335, 222,
       103, 216, 340, 569, 416, 570, 198, 218, 642, 112, 172, 791, 823,
       147, 546, 384, 819, 169, 142, 153, 164, 802, 811, 809, 163, 527,
       140, 189, 519, 767, 186, 853, 394, 889, 847, 133, 778, 134, 520,
       136, 775, 181, 836, 849, 331,  86, 960, 669,  27, 625,  30,  31,
        33, 622, 676, 611, 958,  37, 463, 954, 951,  39, 949,  25, 630,
       974, 299, 450,   3,   4, 639,   6, 648, 989, 987, 985, 294, 983,
       655, 980, 979,  15, 944, 680, 687, 597, 709, 480, 484, 243, 909,
       487, 424, 326, 431, 162, 494,  77, 723,  79, 232, 496, 600, 160,
       930, 921, 922, 924, 695,  57, 436, 474, 603, 287, 351, 451, 263,
       584, 255, 305, 337, 353, 702, 659, 343, 705, 665, 614, 202, 821,
       161, 442,  21, 833, 523, 444, 132, 129,  28, 113, 144, 513, 938,
       437, 926,  59, 882, 898, 827, 418,   5, 152, 814,  13,  10, 441,
       607,   8, 762, 261, 123, 510, 390, 664, 730, 369, 666, 653, 908,
       438, 284, 708, 246, 236, 939,  68, 363, 608, 641, 239, 447, 917,
       916,  53, 646, 491, 720, 432, 941, 254, 699,  20, 981, 636, 280,
       302, 285, 443,   9, 589, 946, 619, 682, 468, 439, 297, 274,   0,
       788, 141,  97, 122, 206,  98, 572, 787, 554, 868, 580, 200, 388,
       838, 841, 347, 188, 765, 742, 517, 818, 886,  88, 383,  91, 336,
       370, 883, 881, 880, 387,  89, 154, 626, 350, 352, 364, 459, 457,
       550, 354, 355, 292, 360, 296, 548, 295, 449, 637, 551, 590, 613,
       461, 435, 372, 333, 492, 585, 328, 423, 489, 324, 428, 998, 601,
       413, 574, 471, 349, 571, 504, 322, 408, 404, 315, 344, 567, 588,
       403, 615, 398, 467, 421, 452, 291, 748, 184, 187,  80, 190, 900,
       195, 196, 203,  76, 747, 780, 904, 905,  73, 913, 735, 221, 731,
        64, 227, 182,  92, 237, 866, 138, 128, 121, 857, 825, 824, 149,
       817, 863, 159, 175, 801, 869, 168, 171, 793, 792,  99, 789,  96,
        62, 840, 933,  40, 955, 683,  34, 268, 269, 273, 276, 278, 970,
       671,  24, 670, 667, 662,  17, 661, 282, 658,  11, 656, 652, 289,
       996, 266, 962, 250, 937, 689, 934,  45, 690, 259, 706, 945, 258,
       392, 105, 107,  67, 110, 440, 400, 407, 429,  46,  50, 430,  56,
       131, 117,  69, 445, 409, 422,  41,  82,  35, 420, 434,  85,  93,
        74, 411, 410,  29,  43, 104,  72, 425,  38, 427, 362, 391, 235,
       248, 244, 325, 240, 238, 327, 332, 212, 233, 229, 225, 334, 219,
       215, 252, 323, 264, 314, 265, 313, 267, 312, 311, 310, 307, 279,
       304, 303, 298, 283, 293, 338, 339, 137, 157, 290, 365, 368, 166,
       373, 374, 377, 211, 156, 385, 386, 143, 139, 389, 361, 173, 174,
       359, 358, 176, 177, 179, 185, 348, 191, 197, 204, 207, 209, 342,
       210, 231, 999, 728, 805, 593, 812, 594, 595, 598, 599, 604, 606,
       803, 627, 612, 795, 617, 790, 786, 620, 623, 785, 592, 813, 587,
       586, 862, 549, 861, 553, 555, 860, 859, 858, 856, 561, 713, 564,
       851, 834, 578, 826, 581, 783, 628, 865, 734, 678, 744, 741, 739,
       738, 736, 685, 686, 732, 779, 692, 729, 693, 454, 697, 726, 722,
       701, 673, 672, 668, 751, 777, 772, 631, 770, 769, 766, 635, 638,
       643, 644, 760, 647, 649, 650, 758, 657, 660, 864, 563, 929, 897,
       524, 522, 966, 518, 911, 476, 914, 977, 478, 515, 915, 514, 923,
       925, 511, 975, 508, 940, 481, 483, 971, 501, 952, 957, 500, 498,
       964, 497, 495, 906, 910, 529, 534, 870, 541, 872, 873, 538, 997,
       877, 455, 878, 995, 879, 894, 993, 884, 490, 986, 990, 988, 470,
       532, 464, 890, 466, 745, 757, 982, 719, 752, 967,  14, 721, 733,
       234, 978, 208, 972, 230, 749, 746, 214,  18,   7, 226, 106, 965,
       126, 150, 148, 891, 887, 830, 831, 845, 125, 764,  90, 124, 854,
        94, 116, 874, 871,  84, 810, 807,  70,  32, 950, 943, 942,  44,
       936, 867, 927, 796, 797, 167, 798,  65, 804, 806, 716, 453, 560,
       624, 557, 629, 301, 300, 632, 357, 634, 640, 552, 645, 286, 493,
       488, 486, 545, 654, 281, 558, 306, 482, 525, 509, 579, 405, 575,
       582, 329, 346, 507, 319, 521, 502, 317, 381, 559, 610, 412, 616,
       526, 341, 543, 473, 472, 684, 462, 262, 433, 382, 540, 376, 247,
       249, 703, 460, 272, 448, 677, 275, 320, 537, 127, 935, 839, 536,
        60, 815,  51,  52, 583, 820,  54, 535, 378, 725, 794, 533, 556,
       753, 754, 109, 542, 479, 194, 102,  16, 963, 475, 193,  83,  26,
       100, 256, 223, 903, 402, 253, 251, 776, 477, 737, 228,  58, 907,
        19, 379, 260, 199, 371, 892, 419,  78, 969, 426,  23, 530,  81,
       973, 976, 932, 401,  12, 984, 531, 469, 458, 991, 992, 456, 994,
       446, 417, 961, 899,  47,  49,  48,  61, 920, 919, 399, 516,  66,
       396, 912, 406, 902, 395, 393, 506, 503, 948, 414, 956,  75, 415,
       959, 947, 707, 876, 761, 675, 205, 277, 750, 755, 756, 651, 192,
       633, 271, 771, 183, 178, 781, 309, 618, 170, 609, 743, 740, 799,
       700, 711, 712, 242, 714, 715, 704, 717, 724, 698, 213, 727, 694,
       691, 220, 688, 681, 679, 270, 316, 800,  95, 118, 848, 566, 565,
       562, 245, 855, 120, 119, 115, 568, 114, 547, 544, 366, 367, 101,
       539, 875, 846, 844, 318, 822, 321, 596, 158, 808, 330, 591, 816,
       151, 146, 843, 145, 828, 829, 576, 835, 837, 135, 842, 499],
      dtype=int64)

In [43]:
## with NN
from sklearn.neighbors import NearestNeighbors

# اول اسم فیلم را از کاربر بگیر
user_movie = input("Enter movie name: ")

# ساخت مدل NN
nn = NearestNeighbors(n_neighbors=5, metric='cosine', algorithm='brute')
nn.fit(result)

# پیدا کردن فیلم‌های مشابه
user_movie_index = df2[df2['Series_Title'] == user_movie].index[0]
user_movie_vector = result[user_movie_index]

distances, indices = nn.kneighbors(user_movie_vector)

# نتیجه (به جز خود فیلم)
recommended_result = indices[0][1:5]
print(df["Series_Title"].iloc[recommended_result])

Enter movie name:  The Dark Knight

155            Batman Begins
774             3:10 to Yuma
36              The Prestige
63     The Dark Knight Rises
Name: Series_Title, dtype: object

In [ ]:
indices

In [ ]:
distances